CONTROL_PROCESSOR_HOST = ''
CHROMECAST_IP = ''
ADB_KEY_PATH = ''
CHROMECAST_ADB_PORT = 0
LIVING_ROOM_PANEL_IPID = 0x00
BEDROOM_PANEL_IPID = 0x00
BEDROOM_TV_IP = ''
BEDROOM_TV_PORT = 0
BEDROOM_TV_TOKEN_FILE_PATH = ''
JOIN_DICT = {
    'sample_join_name' : 0,
}